
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.terribletwo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.terribletwo.TerribletwoMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class TerribletwoModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, TerribletwoMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> TRANSMUTATIONS = REGISTRY.register("transmutations",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.terribletwo.transmutations")).icon(() -> new ItemStack(TerribletwoModItems.COSMIC_KUSH.get())).displayItems((parameters, tabData) -> {
				tabData.accept(TerribletwoModBlocks.PISS_BLOCK.get().asItem());
				tabData.accept(TerribletwoModBlocks.BANANA_TNT.get().asItem());
				tabData.accept(TerribletwoModBlocks.JOE_ROGAN.get().asItem());
				tabData.accept(TerribletwoModBlocks.FLASH_GITZ_ROGAN.get().asItem());
				tabData.accept(TerribletwoModBlocks.STAROF_DAVID_BLOCK.get().asItem());
				tabData.accept(TerribletwoModBlocks.BARREL.get().asItem());
				tabData.accept(TerribletwoModBlocks.TALL_ROD.get().asItem());
				tabData.accept(TerribletwoModBlocks.TALL_ROD_2.get().asItem());
				tabData.accept(TerribletwoModBlocks.ROSE.get().asItem());
				tabData.accept(TerribletwoModBlocks.SKINNY_SHROOM.get().asItem());
				tabData.accept(TerribletwoModBlocks.GOON_SHROOM.get().asItem());
				tabData.accept(TerribletwoModItems.TURTLE_SOUP.get());
				tabData.accept(TerribletwoModItems.SOUR_BERRIES.get());
				tabData.accept(TerribletwoModItems.SLOW_BERRIES.get());
				tabData.accept(TerribletwoModItems.UNDERRIPE_BANANA.get());
				tabData.accept(TerribletwoModItems.BANANA.get());
				tabData.accept(TerribletwoModItems.OVER_RIPEBANANA.get());
				tabData.accept(TerribletwoModItems.ROTTEN_BANANA.get());
				tabData.accept(TerribletwoModItems.COSMIC_SPLIFF.get());
				tabData.accept(TerribletwoModItems.DRAGON_EGG_OMELETTE.get());
				tabData.accept(TerribletwoModItems.PINEAPPLE_PIZZA.get());
				tabData.accept(TerribletwoModItems.THE_INFINITY_PIZZA.get());
				tabData.accept(TerribletwoModItems.CHRISTMAS_COOKIE.get());
				tabData.accept(TerribletwoModItems.BEATROOT.get());
				tabData.accept(TerribletwoModItems.EERALD.get());
				tabData.accept(TerribletwoModItems.WEET.get());
				tabData.accept(TerribletwoModItems.ILLEGAL_PLANE_PART.get());
				tabData.accept(TerribletwoModItems.BASEDTANIUM.get());
				tabData.accept(TerribletwoModItems.FUSION_CUTTER.get());
				tabData.accept(TerribletwoModItems.THE_BLUE_HAT.get());
				tabData.accept(TerribletwoModItems.SONIC_SHOES_BOOTS.get());
				tabData.accept(TerribletwoModItems.BASEDTANIU_ARMOR_HELMET.get());
				tabData.accept(TerribletwoModItems.BASEDTANIU_ARMOR_CHESTPLATE.get());
				tabData.accept(TerribletwoModItems.BASEDTANIU_ARMOR_LEGGINGS.get());
				tabData.accept(TerribletwoModItems.BASEDTANIU_ARMOR_BOOTS.get());
				tabData.accept(TerribletwoModItems.PISS_BUCKET.get());
				tabData.accept(TerribletwoModItems.BOTTLEOF_PISS.get());
				tabData.accept(TerribletwoModItems.SPLASH_BOTTLEOF_PISS.get());
				tabData.accept(TerribletwoModItems.MUG.get());
				tabData.accept(TerribletwoModItems.SEED_PACKET.get());
				tabData.accept(TerribletwoModItems.ADHD_CLOCK.get());
				tabData.accept(TerribletwoModItems.DEPRESSION_CLOCK.get());
				tabData.accept(TerribletwoModItems.THE_RED_BUTTON.get());
				tabData.accept(TerribletwoModItems.CALCULUS_TEXTBOOK.get());
				tabData.accept(TerribletwoModItems.CALC_2_BOOK.get());
				tabData.accept(TerribletwoModItems.CALC_3_BOOK.get());
				tabData.accept(TerribletwoModItems.CALC_4_BOOK.get());
				tabData.accept(TerribletwoModItems.CHAINMAIL_SWORD.get());
				tabData.accept(TerribletwoModItems.BLURPAL_SWORD.get());
				tabData.accept(TerribletwoModItems.GOLDEN_CROWBAR.get());
				tabData.accept(TerribletwoModItems.DIAMOND_CROWBAR.get());
				tabData.accept(TerribletwoModItems.DARK_MATTER_CROWBAR.get());
				tabData.accept(TerribletwoModItems.BASKET.get());
				tabData.accept(TerribletwoModItems.BAUGETTE_MUSKET.get());
				tabData.accept(TerribletwoModItems.GOLDEN_SCAR.get());
				tabData.accept(TerribletwoModItems.LIGHTNING_BOLT.get());
				tabData.accept(TerribletwoModItems.PICKLE_RICK.get());
				tabData.accept(TerribletwoModItems.GRENADE.get());
				tabData.accept(TerribletwoModItems.WALL_GRENADE.get());
				tabData.accept(TerribletwoModItems.BUILDING_WALL_GRENADE.get());
				tabData.accept(TerribletwoModItems.FLOOR_GRENADE.get());
				tabData.accept(TerribletwoModItems.STAIR_GRENADE.get());
				tabData.accept(TerribletwoModItems.CONE_GRENADE.get());
				tabData.accept(TerribletwoModItems.FLASHBANG.get());
				tabData.accept(TerribletwoModItems.BEENADE.get());
				tabData.accept(TerribletwoModItems.BEENADE_2.get());
				tabData.accept(TerribletwoModItems.BEENADE_3.get());
			}).withSearchBar().build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> TERRIBLE_MOD_2 = REGISTRY.register("terrible_mod_2",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.terribletwo.terrible_mod_2")).icon(() -> new ItemStack(TerribletwoModItems.ORIGINS.get())).displayItems((parameters, tabData) -> {
				tabData.accept(TerribletwoModBlocks.SOLID_LEAN.get().asItem());
				tabData.accept(TerribletwoModBlocks.LEAN_BRICKS.get().asItem());
				tabData.accept(TerribletwoModBlocks.LEAN_BRICK_STAIR.get().asItem());
				tabData.accept(TerribletwoModBlocks.LEAN_BRICK_SLAB.get().asItem());
				tabData.accept(TerribletwoModBlocks.LEAN_LIGHT.get().asItem());
				tabData.accept(TerribletwoModBlocks.OURPAL_CHAMBER.get().asItem());
				tabData.accept(TerribletwoModBlocks.FRENCH_BLOCK.get().asItem());
				tabData.accept(TerribletwoModBlocks.RAIN_BLOCK.get().asItem());
				tabData.accept(TerribletwoModBlocks.CRINGETANIUM_ORE.get().asItem());
				tabData.accept(TerribletwoModBlocks.CHAMBEROF_HAN_SOLO.get().asItem());
				tabData.accept(TerribletwoModBlocks.RICHTOFEN.get().asItem());
				tabData.accept(TerribletwoModBlocks.SARCOPHAGUS_BLOCK.get().asItem());
				tabData.accept(TerribletwoModBlocks.SARCOPHAGUS_BLOCK_2.get().asItem());
				tabData.accept(TerribletwoModBlocks.SHAKESPEARE.get().asItem());
				tabData.accept(TerribletwoModItems.GOLDEN_CLAY.get());
				tabData.accept(TerribletwoModItems.LEAN_BUCKET.get());
				tabData.accept(TerribletwoModItems.MOUSTASCHE.get());
				tabData.accept(TerribletwoModItems.WARFSTACHE.get());
				tabData.accept(TerribletwoModItems.LONGPLIER.get());
				tabData.accept(TerribletwoModItems.KISS.get());
				tabData.accept(TerribletwoModItems.THE_REAL_RAIN_KING_DIMENSION.get());
				tabData.accept(TerribletwoModItems.LEAN_CHUNKS.get());
				tabData.accept(TerribletwoModItems.LEAN_BRICK.get());
				tabData.accept(TerribletwoModItems.RAIN.get());
				tabData.accept(TerribletwoModItems.CRINGETANIUM.get());
				tabData.accept(TerribletwoModItems.THE_ORB.get());
				tabData.accept(TerribletwoModItems.COSMIC_KUSH.get());
				tabData.accept(TerribletwoModItems.DEMON_CORE.get());
				tabData.accept(TerribletwoModItems.GOJO_CAT.get());
				tabData.accept(TerribletwoModItems.BAUGETTE.get());
				tabData.accept(TerribletwoModItems.PIZZA.get());
				tabData.accept(TerribletwoModItems.TORN_PAGE_1.get());
				tabData.accept(TerribletwoModItems.TORN_PAGE_2.get());
				tabData.accept(TerribletwoModItems.TORN_PAGE_3.get());
				tabData.accept(TerribletwoModItems.TORN_PAGE_4.get());
				tabData.accept(TerribletwoModItems.TORN_PAGE_5.get());
				tabData.accept(TerribletwoModItems.ORIGINS.get());
				tabData.accept(TerribletwoModItems.SUSBUCKET.get());
				tabData.accept(TerribletwoModItems.DRIPPED_SUSBUCKET.get());
				tabData.accept(TerribletwoModItems.DEAD_SUSBUCKET.get());
				tabData.accept(TerribletwoModItems.C_SPIKE_BOOK.get());
				tabData.accept(TerribletwoModItems.END_FLAMES_BOOK.get());
				tabData.accept(TerribletwoModItems.EMPTY_SCROLL.get());
				tabData.accept(TerribletwoModItems.BARQS.get());
				tabData.accept(TerribletwoModItems.THE_RED_HAT.get());
				tabData.accept(TerribletwoModItems.GUFF_SOUL.get());
				tabData.accept(TerribletwoModItems.KITE.get());
				tabData.accept(TerribletwoModItems.THE_KEY.get());
				tabData.accept(TerribletwoModItems.VOLTSGEIST.get());
				tabData.accept(TerribletwoModItems.CRYSTAL_RAIN.get());
				tabData.accept(TerribletwoModItems.OURPAL_SWORD.get());
				tabData.accept(TerribletwoModItems.REPAIRED_OURPLE_SWORD.get());
				tabData.accept(TerribletwoModItems.UNSTABLE_OURPLE_SWORD.get());
				tabData.accept(TerribletwoModItems.THE_OURPAL_SWORD.get());
				tabData.accept(TerribletwoModItems.CROWBAR.get());
				tabData.accept(TerribletwoModItems.CHRISTMAS_GUN.get());
				tabData.accept(TerribletwoModItems.DL_44.get());
				tabData.accept(TerribletwoModItems.HOLLOW_PURPLE_ITEM.get());
				tabData.accept(TerribletwoModItems.MUSKET.get());
				tabData.accept(TerribletwoModItems.MUSKET_BALL_ITEM.get());
				tabData.accept(TerribletwoModItems.SPEAROF_LONSUSIS.get());
				tabData.accept(TerribletwoModItems.C_SPIKE.get());
				tabData.accept(TerribletwoModItems.END_FLAMES.get());
				tabData.accept(TerribletwoModItems.DT.get());
				tabData.accept(TerribletwoModItems.OURPLE_ARMOR_HELMET.get());
				tabData.accept(TerribletwoModItems.OURPLE_ARMOR_CHESTPLATE.get());
				tabData.accept(TerribletwoModItems.OURPLE_ARMOR_LEGGINGS.get());
				tabData.accept(TerribletwoModItems.OURPLE_ARMOR_BOOTS.get());
				tabData.accept(TerribletwoModItems.CRINGETANIUM_ARMOR_ARMOR_HELMET.get());
				tabData.accept(TerribletwoModItems.CRINGETANIUM_ARMOR_ARMOR_CHESTPLATE.get());
				tabData.accept(TerribletwoModItems.CRINGETANIUM_ARMOR_ARMOR_LEGGINGS.get());
				tabData.accept(TerribletwoModItems.CRINGETANIUM_ARMOR_ARMOR_BOOTS.get());
				tabData.accept(TerribletwoModItems.GODS_SHOES_BOOTS.get());
				tabData.accept(TerribletwoModItems.GOJO_BLINDFOLD_HELMET.get());
				tabData.accept(TerribletwoModItems.NAPOLEON_PANTS_LEGGINGS.get());
				tabData.accept(TerribletwoModItems.FREDDY_CHESTPLATE_CHESTPLATE.get());
				tabData.accept(TerribletwoModItems.SUNKEN_STAR.get());
				tabData.accept(TerribletwoModItems.THE_CREATOR.get());
				tabData.accept(TerribletwoModItems.GECKOS_EYE.get());
				tabData.accept(TerribletwoModItems.DIABOLIST_FLAMES.get());
				tabData.accept(TerribletwoModItems.OLD_SPICE.get());
				tabData.accept(TerribletwoModItems.BABOON_KING_STAFF.get());
				tabData.accept(TerribletwoModItems.DRACULA_FLOW.get());
				tabData.accept(TerribletwoModItems.THE_ANTHOLOGY.get());
				tabData.accept(TerribletwoModItems.FIR.get());
				tabData.accept(TerribletwoModItems.SHADOW_WIZARD_MONEY_GANG_SONG.get());
				tabData.accept(TerribletwoModItems.VVLOPERS.get());
				tabData.accept(TerribletwoModItems.GOJO_MUSIC.get());
				tabData.accept(TerribletwoModItems.NAP_DISC.get());
				tabData.accept(TerribletwoModItems.FRENCH_DISC.get());
				tabData.accept(TerribletwoModItems.NFFNN.get());
				tabData.accept(TerribletwoModItems.TWELVE.get());
				tabData.accept(TerribletwoModItems.STRONGER_THAN_YOU.get());
				tabData.accept(TerribletwoModItems.NOBODYS_HERO.get());
				tabData.accept(TerribletwoModItems.MIMIC_SONG.get());
				tabData.accept(TerribletwoModItems.MINING_DIAMONDS.get());
				tabData.accept(TerribletwoModItems.PLACING_BLOCKS.get());
				tabData.accept(TerribletwoModItems.LIVING_TOMBSTONE.get());
				tabData.accept(TerribletwoModItems.WEEZER.get());
				tabData.accept(TerribletwoModItems.THE_END.get());
				tabData.accept(TerribletwoModItems.SECRET_ENDING.get());
				tabData.accept(TerribletwoModItems.YELL.get());
				tabData.accept(TerribletwoModItems.DREAM_MEMORY.get());
				tabData.accept(TerribletwoModItems.FROZEN_APE.get());
				tabData.accept(TerribletwoModItems.BEDBUG_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GERMAN_MAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.LIL_GRAY_ALIEN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.WILLIAM_AFTON_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GOD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.ATHLETIC_STEVE_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_WIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_V_VIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_PURPLE_WIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_RED_WIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_GREEN_WIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_YELLOW_WIZARD_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.HALF_LIFE_SCIENTIST_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.THE_VILLIAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GOLDEN_VILLIAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.DIAMOND_VILLIAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.DARK_MATTER_VILLIAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GOJO_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.NAPOLEON_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.NAPOLEONIC_SOLDIER_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.FREDDY_FAZBEAR_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.HYPER_REALISTIC_FREDDY_FAZBEAR_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.BONNIE_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.CHICA_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.FOXY_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GOLDEN_FREDDY_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.SPRINGTRAP_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.MARKIPLIER_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.MARKET_PLIER_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.SANTA_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GREEN_ELF_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.RED_ELF_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.RENAISSANCE_MAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.SUSMONGUS_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.DRIPPED_OUT_SUSMONGUS_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.KANYE_WEST_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.SS_GOLEM_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.GONK_DROID_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.C_SHAPE_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.PEEPEE_MAN_SPAWN_EGG.get());
				tabData.accept(TerribletwoModItems.BABOON_SPAWN_EGG.get());
			}).withSearchBar().build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.SPAWN_EGGS) {
			tabData.accept(TerribletwoModItems.BEATKING_SPAWN_EGG.get());
		}
	}
}
