
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.terribletwo.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.core.registries.BuiltInRegistries;

import net.mcreator.terribletwo.item.YellItem;
import net.mcreator.terribletwo.item.WeezerItem;
import net.mcreator.terribletwo.item.WeetItem;
import net.mcreator.terribletwo.item.WarfstacheItem;
import net.mcreator.terribletwo.item.WallGrenadeItem;
import net.mcreator.terribletwo.item.VvlopersItem;
import net.mcreator.terribletwo.item.VoltsgeistItem;
import net.mcreator.terribletwo.item.UnstableOurpleSwordItem;
import net.mcreator.terribletwo.item.UnderripeBananaItem;
import net.mcreator.terribletwo.item.TwelveItem;
import net.mcreator.terribletwo.item.TurtleSoupItem;
import net.mcreator.terribletwo.item.TornPage5Item;
import net.mcreator.terribletwo.item.TornPage4Item;
import net.mcreator.terribletwo.item.TornPage3Item;
import net.mcreator.terribletwo.item.TornPage2Item;
import net.mcreator.terribletwo.item.TornPage1Item;
import net.mcreator.terribletwo.item.TheRedHatItem;
import net.mcreator.terribletwo.item.TheRedButtonItem;
import net.mcreator.terribletwo.item.TheRealRainKingDimensionItem;
import net.mcreator.terribletwo.item.TheOurpalSwordItem;
import net.mcreator.terribletwo.item.TheOrbItem;
import net.mcreator.terribletwo.item.TheKeyItem;
import net.mcreator.terribletwo.item.TheInfinityPizzaItem;
import net.mcreator.terribletwo.item.TheEndItem;
import net.mcreator.terribletwo.item.TheCreatorItem;
import net.mcreator.terribletwo.item.TheBlueHatItem;
import net.mcreator.terribletwo.item.TheAnthologyItem;
import net.mcreator.terribletwo.item.SusbucketItem;
import net.mcreator.terribletwo.item.SunkenStarItem;
import net.mcreator.terribletwo.item.StrongerThanYouItem;
import net.mcreator.terribletwo.item.StairGrenadeItem;
import net.mcreator.terribletwo.item.SplashBottleofPissItem;
import net.mcreator.terribletwo.item.SpearofLonsusisItem;
import net.mcreator.terribletwo.item.SourBerriesItem;
import net.mcreator.terribletwo.item.SonicShoesItem;
import net.mcreator.terribletwo.item.SlowBerriesItem;
import net.mcreator.terribletwo.item.ShadowWizardMoneyGangSongItem;
import net.mcreator.terribletwo.item.SeedPacketItem;
import net.mcreator.terribletwo.item.SecretEndingItem;
import net.mcreator.terribletwo.item.RottenBananaItem;
import net.mcreator.terribletwo.item.RepairedOurpleSwordItem;
import net.mcreator.terribletwo.item.RainItem;
import net.mcreator.terribletwo.item.PlacingBlocksItem;
import net.mcreator.terribletwo.item.PizzaItem;
import net.mcreator.terribletwo.item.PissItem;
import net.mcreator.terribletwo.item.PineapplePizzaItem;
import net.mcreator.terribletwo.item.PickleRickItem;
import net.mcreator.terribletwo.item.OverRipebananaItem;
import net.mcreator.terribletwo.item.OurpleArmorItem;
import net.mcreator.terribletwo.item.OurpalSwordItem;
import net.mcreator.terribletwo.item.OriginsItem;
import net.mcreator.terribletwo.item.OldSpiceItem;
import net.mcreator.terribletwo.item.NukeiItem;
import net.mcreator.terribletwo.item.NobodysHeroItem;
import net.mcreator.terribletwo.item.NapoleonPantsItem;
import net.mcreator.terribletwo.item.NapDiscItem;
import net.mcreator.terribletwo.item.NFFNNItem;
import net.mcreator.terribletwo.item.MusketItem;
import net.mcreator.terribletwo.item.MusketBallItemItem;
import net.mcreator.terribletwo.item.MugItem;
import net.mcreator.terribletwo.item.MoustascheItem;
import net.mcreator.terribletwo.item.MoneyiItem;
import net.mcreator.terribletwo.item.MiningDiamondsItem;
import net.mcreator.terribletwo.item.MimicSongItem;
import net.mcreator.terribletwo.item.LongplierItem;
import net.mcreator.terribletwo.item.LivingTombstoneItem;
import net.mcreator.terribletwo.item.LightningBoltItem;
import net.mcreator.terribletwo.item.LeanItem;
import net.mcreator.terribletwo.item.LeanChunksItem;
import net.mcreator.terribletwo.item.LeanBrickItem;
import net.mcreator.terribletwo.item.LaserItem;
import net.mcreator.terribletwo.item.KiteItem;
import net.mcreator.terribletwo.item.KissItem;
import net.mcreator.terribletwo.item.IllegalPlanePartItem;
import net.mcreator.terribletwo.item.HollowPurpleItemItem;
import net.mcreator.terribletwo.item.GuffSoulItem;
import net.mcreator.terribletwo.item.GrenadeItem;
import net.mcreator.terribletwo.item.GoldenScarItem;
import net.mcreator.terribletwo.item.GoldenCrowbarItem;
import net.mcreator.terribletwo.item.GoldenClayItem;
import net.mcreator.terribletwo.item.GojoMusicItem;
import net.mcreator.terribletwo.item.GojoCatItem;
import net.mcreator.terribletwo.item.GojoBlindfoldItem;
import net.mcreator.terribletwo.item.GodsShoesItem;
import net.mcreator.terribletwo.item.GlockiItem;
import net.mcreator.terribletwo.item.GeckosEyeItem;
import net.mcreator.terribletwo.item.FusionCutterItem;
import net.mcreator.terribletwo.item.FrozenApeItem;
import net.mcreator.terribletwo.item.FrenchDiscItem;
import net.mcreator.terribletwo.item.FreddyChestplateItem;
import net.mcreator.terribletwo.item.FloorGrenadeItem;
import net.mcreator.terribletwo.item.FlashbangItem;
import net.mcreator.terribletwo.item.FirItem;
import net.mcreator.terribletwo.item.FakemusketballItem;
import net.mcreator.terribletwo.item.FakeSpearItem;
import net.mcreator.terribletwo.item.EndFlamesItem;
import net.mcreator.terribletwo.item.EndFlamesBookItem;
import net.mcreator.terribletwo.item.EmptyScrollItem;
import net.mcreator.terribletwo.item.EeraldItem;
import net.mcreator.terribletwo.item.DtItem;
import net.mcreator.terribletwo.item.DrippedSusbucketItem;
import net.mcreator.terribletwo.item.DreamMemoryItem;
import net.mcreator.terribletwo.item.DragonEggOmeletteItem;
import net.mcreator.terribletwo.item.DraculaFlowItem;
import net.mcreator.terribletwo.item.DiamondCrowbarItem;
import net.mcreator.terribletwo.item.DiabolistFlamesItem;
import net.mcreator.terribletwo.item.DepressionClockItem;
import net.mcreator.terribletwo.item.DemonCoreItem;
import net.mcreator.terribletwo.item.DeadSusbucketItem;
import net.mcreator.terribletwo.item.DarkMatterCrowbarItem;
import net.mcreator.terribletwo.item.DL44Item;
import net.mcreator.terribletwo.item.CrystalRainItem;
import net.mcreator.terribletwo.item.CrowbarItem;
import net.mcreator.terribletwo.item.CringetaniumItem;
import net.mcreator.terribletwo.item.CringetaniumArmorArmorItem;
import net.mcreator.terribletwo.item.CosmicSpliffItem;
import net.mcreator.terribletwo.item.CosmicKushItem;
import net.mcreator.terribletwo.item.ConeGrenadeItem;
import net.mcreator.terribletwo.item.ChristmasGunItem;
import net.mcreator.terribletwo.item.ChristmasCookieItem;
import net.mcreator.terribletwo.item.ChainmailSwordItem;
import net.mcreator.terribletwo.item.CalculusTextbookItem;
import net.mcreator.terribletwo.item.Calc4BookItem;
import net.mcreator.terribletwo.item.Calc3BookItem;
import net.mcreator.terribletwo.item.Calc2BookItem;
import net.mcreator.terribletwo.item.CSpikeItem;
import net.mcreator.terribletwo.item.CSpikeBookItem;
import net.mcreator.terribletwo.item.BulletItem;
import net.mcreator.terribletwo.item.BuildingWallGrenadeItem;
import net.mcreator.terribletwo.item.BottleofPissItem;
import net.mcreator.terribletwo.item.BoosSmallFireballItem;
import net.mcreator.terribletwo.item.BlurpalSwordItem;
import net.mcreator.terribletwo.item.BeenadeItem;
import net.mcreator.terribletwo.item.Beenade3Item;
import net.mcreator.terribletwo.item.Beenade2Item;
import net.mcreator.terribletwo.item.BeatrootItem;
import net.mcreator.terribletwo.item.BaugetteMusketItem;
import net.mcreator.terribletwo.item.BaugetteItem;
import net.mcreator.terribletwo.item.BasketItem;
import net.mcreator.terribletwo.item.BasedtaniumItem;
import net.mcreator.terribletwo.item.BasedtaniuArmorItem;
import net.mcreator.terribletwo.item.BarqsItem;
import net.mcreator.terribletwo.item.BananaItem;
import net.mcreator.terribletwo.item.BaboonKingStaffItem;
import net.mcreator.terribletwo.item.ADHDClockItem;
import net.mcreator.terribletwo.TerribletwoMod;

public class TerribletwoModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, TerribletwoMod.MODID);
	public static final DeferredHolder<Item, Item> DRACULA_FLOW = REGISTRY.register("dracula_flow", DraculaFlowItem::new);
	public static final DeferredHolder<Item, Item> WILLIAM_AFTON_SPAWN_EGG = REGISTRY.register("william_afton_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.WILLIAM_AFTON, -6723841, -6723841, new Item.Properties()));
	public static final DeferredHolder<Item, Item> THE_ANTHOLOGY = REGISTRY.register("the_anthology", TheAnthologyItem::new);
	public static final DeferredHolder<Item, Item> LEAN_BUCKET = REGISTRY.register("lean_bucket", LeanItem::new);
	public static final DeferredHolder<Item, Item> FIR = REGISTRY.register("fir", FirItem::new);
	public static final DeferredHolder<Item, Item> LIL_GRAY_ALIEN_SPAWN_EGG = REGISTRY.register("lil_gray_alien_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.LIL_GRAY_ALIEN, -3355444, -3355444, new Item.Properties()));
	public static final DeferredHolder<Item, Item> LASER = REGISTRY.register("laser", LaserItem::new);
	public static final DeferredHolder<Item, Item> DL_44 = REGISTRY.register("dl_44", DL44Item::new);
	public static final DeferredHolder<Item, Item> DT = REGISTRY.register("dt", DtItem::new);
	public static final DeferredHolder<Item, Item> LEAN_CHUNKS = REGISTRY.register("lean_chunks", LeanChunksItem::new);
	public static final DeferredHolder<Item, Item> SOLID_LEAN = block(TerribletwoModBlocks.SOLID_LEAN);
	public static final DeferredHolder<Item, Item> THE_ORB = REGISTRY.register("the_orb", TheOrbItem::new);
	public static final DeferredHolder<Item, Item> SHADOW_WIZARD_MONEY_GANG_SONG = REGISTRY.register("shadow_wizard_money_gang_song", ShadowWizardMoneyGangSongItem::new);
	public static final DeferredHolder<Item, Item> OURPAL_SWORD = REGISTRY.register("ourpal_sword", OurpalSwordItem::new);
	public static final DeferredHolder<Item, Item> THE_WIZARD_SPAWN_EGG = REGISTRY.register("the_wizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_WIZARD, -1572353, -13696769, new Item.Properties()));
	public static final DeferredHolder<Item, Item> THE_V_VIZARD_SPAWN_EGG = REGISTRY.register("the_v_vizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_V_VIZARD, -16383745, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> COSMIC_KUSH = REGISTRY.register("cosmic_kush", CosmicKushItem::new);
	public static final DeferredHolder<Item, Item> THE_PURPLE_WIZARD_SPAWN_EGG = REGISTRY.register("the_purple_wizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_PURPLE_WIZARD, -6736897, -6736897, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BULLET = REGISTRY.register("bullet", BulletItem::new);
	public static final DeferredHolder<Item, Item> GLOCKI = REGISTRY.register("glocki", GlockiItem::new);
	public static final DeferredHolder<Item, Item> THE_RED_WIZARD_SPAWN_EGG = REGISTRY.register("the_red_wizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_RED_WIZARD, -65536, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> THE_GREEN_WIZARD_SPAWN_EGG = REGISTRY.register("the_green_wizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_GREEN_WIZARD, -16711885, -16711885, new Item.Properties()));
	public static final DeferredHolder<Item, Item> NUKEI = REGISTRY.register("nukei", NukeiItem::new);
	public static final DeferredHolder<Item, Item> THE_YELLOW_WIZARD_SPAWN_EGG = REGISTRY.register("the_yellow_wizard_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_YELLOW_WIZARD, -205, -205, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MONEYI = REGISTRY.register("moneyi", MoneyiItem::new);
	public static final DeferredHolder<Item, Item> OURPLE_ARMOR_HELMET = REGISTRY.register("ourple_armor_helmet", OurpleArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> OURPLE_ARMOR_CHESTPLATE = REGISTRY.register("ourple_armor_chestplate", OurpleArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> OURPLE_ARMOR_LEGGINGS = REGISTRY.register("ourple_armor_leggings", OurpleArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> OURPLE_ARMOR_BOOTS = REGISTRY.register("ourple_armor_boots", OurpleArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> GERMAN_MAN_SPAWN_EGG = REGISTRY.register("german_man_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GERMAN_MAN, -16737844, -16776961, new Item.Properties()));
	public static final DeferredHolder<Item, Item> THE_OURPAL_SWORD = REGISTRY.register("the_ourpal_sword", TheOurpalSwordItem::new);
	public static final DeferredHolder<Item, Item> GOD_SPAWN_EGG = REGISTRY.register("god_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GOD, -3381760, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BASKET = REGISTRY.register("basket", BasketItem::new);
	public static final DeferredHolder<Item, Item> GODS_SHOES_BOOTS = REGISTRY.register("gods_shoes_boots", GodsShoesItem.Boots::new);
	public static final DeferredHolder<Item, Item> OURPAL_CHAMBER = block(TerribletwoModBlocks.OURPAL_CHAMBER);
	public static final DeferredHolder<Item, Item> LEAN_BRICKS = block(TerribletwoModBlocks.LEAN_BRICKS);
	public static final DeferredHolder<Item, Item> LEAN_BRICK_SLAB = block(TerribletwoModBlocks.LEAN_BRICK_SLAB);
	public static final DeferredHolder<Item, Item> LEAN_BRICK_STAIR = block(TerribletwoModBlocks.LEAN_BRICK_STAIR);
	public static final DeferredHolder<Item, Item> LEAN_LIGHT = block(TerribletwoModBlocks.LEAN_LIGHT);
	public static final DeferredHolder<Item, Item> UNSTABLE_OURPLE_SWORD = REGISTRY.register("unstable_ourple_sword", UnstableOurpleSwordItem::new);
	public static final DeferredHolder<Item, Item> HALF_LIFE_SCIENTIST_SPAWN_EGG = REGISTRY.register("half_life_scientist_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.HALF_LIFE_SCIENTIST, -39424, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CROWBAR = REGISTRY.register("crowbar", CrowbarItem::new);
	public static final DeferredHolder<Item, Item> THE_VILLIAN_SPAWN_EGG = REGISTRY.register("the_villian_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.THE_VILLIAN, -65536, -3407872, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DEMON_CORE = REGISTRY.register("demon_core", DemonCoreItem::new);
	public static final DeferredHolder<Item, Item> RAIN_BLOCK = block(TerribletwoModBlocks.RAIN_BLOCK);
	public static final DeferredHolder<Item, Item> RAIN = REGISTRY.register("rain", RainItem::new);
	public static final DeferredHolder<Item, Item> THE_REAL_RAIN_KING_DIMENSION = REGISTRY.register("the_real_rain_king_dimension", TheRealRainKingDimensionItem::new);
	public static final DeferredHolder<Item, Item> KISS = REGISTRY.register("kiss", KissItem::new);
	public static final DeferredHolder<Item, Item> REPAIRED_OURPLE_SWORD = REGISTRY.register("repaired_ourple_sword", RepairedOurpleSwordItem::new);
	public static final DeferredHolder<Item, Item> CRINGETANIUM = REGISTRY.register("cringetanium", CringetaniumItem::new);
	public static final DeferredHolder<Item, Item> CRINGETANIUM_ORE = block(TerribletwoModBlocks.CRINGETANIUM_ORE);
	public static final DeferredHolder<Item, Item> CHAMBEROF_HAN_SOLO = block(TerribletwoModBlocks.CHAMBEROF_HAN_SOLO);
	public static final DeferredHolder<Item, Item> CRINGETANIUM_ARMOR_ARMOR_HELMET = REGISTRY.register("cringetanium_armor_armor_helmet", CringetaniumArmorArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> CRINGETANIUM_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("cringetanium_armor_armor_chestplate", CringetaniumArmorArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> CRINGETANIUM_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("cringetanium_armor_armor_leggings", CringetaniumArmorArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> CRINGETANIUM_ARMOR_ARMOR_BOOTS = REGISTRY.register("cringetanium_armor_armor_boots", CringetaniumArmorArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> BARQS = REGISTRY.register("barqs", BarqsItem::new);
	public static final DeferredHolder<Item, Item> RENAISSANCE_MAN_SPAWN_EGG = REGISTRY.register("renaissance_man_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.RENAISSANCE_MAN, -6737152, -16750951, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GOJO_SPAWN_EGG = REGISTRY.register("gojo_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GOJO, -16777165, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GOJO_BLINDFOLD_HELMET = REGISTRY.register("gojo_blindfold_helmet", GojoBlindfoldItem.Helmet::new);
	public static final DeferredHolder<Item, Item> HOLLOW_PURPLE_ITEM = REGISTRY.register("hollow_purple_item", HollowPurpleItemItem::new);
	public static final DeferredHolder<Item, Item> SS_GOLEM_SPAWN_EGG = REGISTRY.register("ss_golem_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.SS_GOLEM, -65536, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MUG = REGISTRY.register("mug", MugItem::new);
	public static final DeferredHolder<Item, Item> ADHD_CLOCK = REGISTRY.register("adhd_clock", ADHDClockItem::new);
	public static final DeferredHolder<Item, Item> DEPRESSION_CLOCK = REGISTRY.register("depression_clock", DepressionClockItem::new);
	public static final DeferredHolder<Item, Item> COSMIC_SPLIFF = REGISTRY.register("cosmic_spliff", CosmicSpliffItem::new);
	public static final DeferredHolder<Item, Item> BASEDTANIUM = REGISTRY.register("basedtanium", BasedtaniumItem::new);
	public static final DeferredHolder<Item, Item> BASEDTANIU_ARMOR_HELMET = REGISTRY.register("basedtaniu_armor_helmet", BasedtaniuArmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> BASEDTANIU_ARMOR_CHESTPLATE = REGISTRY.register("basedtaniu_armor_chestplate", BasedtaniuArmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> BASEDTANIU_ARMOR_LEGGINGS = REGISTRY.register("basedtaniu_armor_leggings", BasedtaniuArmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> BASEDTANIU_ARMOR_BOOTS = REGISTRY.register("basedtaniu_armor_boots", BasedtaniuArmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOJO_CAT = REGISTRY.register("gojo_cat", GojoCatItem::new);
	public static final DeferredHolder<Item, Item> NAPOLEON_SPAWN_EGG = REGISTRY.register("napoleon_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.NAPOLEON, -16763956, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> VVLOPERS = REGISTRY.register("vvlopers", VvlopersItem::new);
	public static final DeferredHolder<Item, Item> SPEAROF_LONSUSIS = REGISTRY.register("spearof_lonsusis", SpearofLonsusisItem::new);
	public static final DeferredHolder<Item, Item> GOJO_MUSIC = REGISTRY.register("gojo_music", GojoMusicItem::new);
	public static final DeferredHolder<Item, Item> NAP_DISC = REGISTRY.register("nap_disc", NapDiscItem::new);
	public static final DeferredHolder<Item, Item> THE_END = REGISTRY.register("the_end", TheEndItem::new);
	public static final DeferredHolder<Item, Item> NAPOLEONIC_SOLDIER_SPAWN_EGG = REGISTRY.register("napoleonic_soldier_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.NAPOLEONIC_SOLDIER, -52429, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FUSION_CUTTER = REGISTRY.register("fusion_cutter", FusionCutterItem::new);
	public static final DeferredHolder<Item, Item> GOLDEN_CROWBAR = REGISTRY.register("golden_crowbar", GoldenCrowbarItem::new);
	public static final DeferredHolder<Item, Item> FAKEMUSKETBALL = REGISTRY.register("fakemusketball", FakemusketballItem::new);
	public static final DeferredHolder<Item, Item> MUSKET = REGISTRY.register("musket", MusketItem::new);
	public static final DeferredHolder<Item, Item> FRENCH_DISC = REGISTRY.register("french_disc", FrenchDiscItem::new);
	public static final DeferredHolder<Item, Item> BAUGETTE = REGISTRY.register("baugette", BaugetteItem::new);
	public static final DeferredHolder<Item, Item> THE_CREATOR = REGISTRY.register("the_creator", TheCreatorItem::new);
	public static final DeferredHolder<Item, Item> SUNKEN_STAR = REGISTRY.register("sunken_star", SunkenStarItem::new);
	public static final DeferredHolder<Item, Item> GECKOS_EYE = REGISTRY.register("geckos_eye", GeckosEyeItem::new);
	public static final DeferredHolder<Item, Item> DIABOLIST_FLAMES = REGISTRY.register("diabolist_flames", DiabolistFlamesItem::new);
	public static final DeferredHolder<Item, Item> BABOON_KING_STAFF = REGISTRY.register("baboon_king_staff", BaboonKingStaffItem::new);
	public static final DeferredHolder<Item, Item> BABOON_SPAWN_EGG = REGISTRY.register("baboon_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.BABOON, -16763956, -39322, new Item.Properties()));
	public static final DeferredHolder<Item, Item> OLD_SPICE = REGISTRY.register("old_spice", OldSpiceItem::new);
	public static final DeferredHolder<Item, Item> FREDDY_FAZBEAR_SPAWN_EGG = REGISTRY.register("freddy_fazbear_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.FREDDY_FAZBEAR, -10079488, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BONNIE_SPAWN_EGG = REGISTRY.register("bonnie_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.BONNIE, -10092391, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CHICA_SPAWN_EGG = REGISTRY.register("chica_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.CHICA, -256, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FOXY_SPAWN_EGG = REGISTRY.register("foxy_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.FOXY, -65536, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> PIZZA = REGISTRY.register("pizza", PizzaItem::new);
	public static final DeferredHolder<Item, Item> HYPER_REALISTIC_FREDDY_FAZBEAR_SPAWN_EGG = REGISTRY.register("hyper_realistic_freddy_fazbear_spawn_egg",
			() -> new DeferredSpawnEggItem(TerribletwoModEntities.HYPER_REALISTIC_FREDDY_FAZBEAR, -10079488, -10092544, new Item.Properties()));
	public static final DeferredHolder<Item, Item> ORIGINS = REGISTRY.register("origins", OriginsItem::new);
	public static final DeferredHolder<Item, Item> RICHTOFEN = block(TerribletwoModBlocks.RICHTOFEN);
	public static final DeferredHolder<Item, Item> TORN_PAGE_1 = REGISTRY.register("torn_page_1", TornPage1Item::new);
	public static final DeferredHolder<Item, Item> TORN_PAGE_2 = REGISTRY.register("torn_page_2", TornPage2Item::new);
	public static final DeferredHolder<Item, Item> TORN_PAGE_3 = REGISTRY.register("torn_page_3", TornPage3Item::new);
	public static final DeferredHolder<Item, Item> NAPOLEON_PANTS_LEGGINGS = REGISTRY.register("napoleon_pants_leggings", NapoleonPantsItem.Leggings::new);
	public static final DeferredHolder<Item, Item> NFFNN = REGISTRY.register("nffnn", NFFNNItem::new);
	public static final DeferredHolder<Item, Item> FREDDY_CHESTPLATE_CHESTPLATE = REGISTRY.register("freddy_chestplate_chestplate", FreddyChestplateItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> SUSMONGUS_SPAWN_EGG = REGISTRY.register("susmongus_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.SUSMONGUS, -65536, -16724788, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GONK_DROID_SPAWN_EGG = REGISTRY.register("gonk_droid_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GONK_DROID, -13421773, -10066330, new Item.Properties()));
	public static final DeferredHolder<Item, Item> CALCULUS_TEXTBOOK = REGISTRY.register("calculus_textbook", CalculusTextbookItem::new);
	public static final DeferredHolder<Item, Item> CALC_2_BOOK = REGISTRY.register("calc_2_book", Calc2BookItem::new);
	public static final DeferredHolder<Item, Item> CALC_3_BOOK = REGISTRY.register("calc_3_book", Calc3BookItem::new);
	public static final DeferredHolder<Item, Item> CALC_4_BOOK = REGISTRY.register("calc_4_book", Calc4BookItem::new);
	public static final DeferredHolder<Item, Item> TWELVE = REGISTRY.register("twelve", TwelveItem::new);
	public static final DeferredHolder<Item, Item> BAUGETTE_MUSKET = REGISTRY.register("baugette_musket", BaugetteMusketItem::new);
	public static final DeferredHolder<Item, Item> PISS_BUCKET = REGISTRY.register("piss_bucket", PissItem::new);
	public static final DeferredHolder<Item, Item> KANYE_WEST_SPAWN_EGG = REGISTRY.register("kanye_west_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.KANYE_WEST, -65536, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> FRENCH_BLOCK = block(TerribletwoModBlocks.FRENCH_BLOCK);
	public static final DeferredHolder<Item, Item> BEDBUG_SPAWN_EGG = REGISTRY.register("bedbug_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.BEDBUG, -10079488, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> JOE_ROGAN = block(TerribletwoModBlocks.JOE_ROGAN);
	public static final DeferredHolder<Item, Item> FLASH_GITZ_ROGAN = block(TerribletwoModBlocks.FLASH_GITZ_ROGAN);
	public static final DeferredHolder<Item, Item> THE_RED_HAT = REGISTRY.register("the_red_hat", TheRedHatItem::new);
	public static final DeferredHolder<Item, Item> THE_INFINITY_PIZZA = REGISTRY.register("the_infinity_pizza", TheInfinityPizzaItem::new);
	public static final DeferredHolder<Item, Item> THE_BLUE_HAT = REGISTRY.register("the_blue_hat", TheBlueHatItem::new);
	public static final DeferredHolder<Item, Item> BLURPAL_SWORD = REGISTRY.register("blurpal_sword", BlurpalSwordItem::new);
	public static final DeferredHolder<Item, Item> ILLEGAL_PLANE_PART = REGISTRY.register("illegal_plane_part", IllegalPlanePartItem::new);
	public static final DeferredHolder<Item, Item> LEAN_BRICK = REGISTRY.register("lean_brick", LeanBrickItem::new);
	public static final DeferredHolder<Item, Item> PINEAPPLE_PIZZA = REGISTRY.register("pineapple_pizza", PineapplePizzaItem::new);
	public static final DeferredHolder<Item, Item> DIAMOND_CROWBAR = REGISTRY.register("diamond_crowbar", DiamondCrowbarItem::new);
	public static final DeferredHolder<Item, Item> DARK_MATTER_CROWBAR = REGISTRY.register("dark_matter_crowbar", DarkMatterCrowbarItem::new);
	public static final DeferredHolder<Item, Item> BANANA = REGISTRY.register("banana", BananaItem::new);
	public static final DeferredHolder<Item, Item> OVER_RIPEBANANA = REGISTRY.register("over_ripebanana", OverRipebananaItem::new);
	public static final DeferredHolder<Item, Item> ROTTEN_BANANA = REGISTRY.register("rotten_banana", RottenBananaItem::new);
	public static final DeferredHolder<Item, Item> UNDERRIPE_BANANA = REGISTRY.register("underripe_banana", UnderripeBananaItem::new);
	public static final DeferredHolder<Item, Item> BANANA_TNT = block(TerribletwoModBlocks.BANANA_TNT);
	public static final DeferredHolder<Item, Item> SEED_PACKET = REGISTRY.register("seed_packet", SeedPacketItem::new);
	public static final DeferredHolder<Item, Item> YELL = REGISTRY.register("yell", YellItem::new);
	public static final DeferredHolder<Item, Item> DREAM_MEMORY = REGISTRY.register("dream_memory", DreamMemoryItem::new);
	public static final DeferredHolder<Item, Item> FROZEN_APE = REGISTRY.register("frozen_ape", FrozenApeItem::new);
	public static final DeferredHolder<Item, Item> EMPTY_SCROLL = REGISTRY.register("empty_scroll", EmptyScrollItem::new);
	public static final DeferredHolder<Item, Item> CHAINMAIL_SWORD = REGISTRY.register("chainmail_sword", ChainmailSwordItem::new);
	public static final DeferredHolder<Item, Item> PISS_BLOCK = block(TerribletwoModBlocks.PISS_BLOCK);
	public static final DeferredHolder<Item, Item> BOTTLEOF_PISS = REGISTRY.register("bottleof_piss", BottleofPissItem::new);
	public static final DeferredHolder<Item, Item> SPLASH_BOTTLEOF_PISS = REGISTRY.register("splash_bottleof_piss", SplashBottleofPissItem::new);
	public static final DeferredHolder<Item, Item> KITE = REGISTRY.register("kite", KiteItem::new);
	public static final DeferredHolder<Item, Item> THE_KEY = REGISTRY.register("the_key", TheKeyItem::new);
	public static final DeferredHolder<Item, Item> VOLTSGEIST = REGISTRY.register("voltsgeist", VoltsgeistItem::new);
	public static final DeferredHolder<Item, Item> DRIPPED_OUT_SUSMONGUS_SPAWN_EGG = REGISTRY.register("dripped_out_susmongus_spawn_egg",
			() -> new DeferredSpawnEggItem(TerribletwoModEntities.DRIPPED_OUT_SUSMONGUS, -1, -3407872, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GOLDEN_VILLIAN_SPAWN_EGG = REGISTRY.register("golden_villian_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GOLDEN_VILLIAN, -256, -13312, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DIAMOND_VILLIAN_SPAWN_EGG = REGISTRY.register("diamond_villian_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.DIAMOND_VILLIAN, -16711681, -16724737, new Item.Properties()));
	public static final DeferredHolder<Item, Item> DARK_MATTER_VILLIAN_SPAWN_EGG = REGISTRY.register("dark_matter_villian_spawn_egg",
			() -> new DeferredSpawnEggItem(TerribletwoModEntities.DARK_MATTER_VILLIAN, -6749953, -10092391, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MARKIPLIER_SPAWN_EGG = REGISTRY.register("markiplier_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.MARKIPLIER, -65360, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> MARKET_PLIER_SPAWN_EGG = REGISTRY.register("market_plier_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.MARKET_PLIER, -13434880, -65536, new Item.Properties()));
	public static final DeferredHolder<Item, Item> TORN_PAGE_4 = REGISTRY.register("torn_page_4", TornPage4Item::new);
	public static final DeferredHolder<Item, Item> DRAGON_EGG_OMELETTE = REGISTRY.register("dragon_egg_omelette", DragonEggOmeletteItem::new);
	public static final DeferredHolder<Item, Item> CHRISTMAS_GUN = REGISTRY.register("christmas_gun", ChristmasGunItem::new);
	public static final DeferredHolder<Item, Item> FAKE_SPEAR = REGISTRY.register("fake_spear", FakeSpearItem::new);
	public static final DeferredHolder<Item, Item> TORN_PAGE_5 = REGISTRY.register("torn_page_5", TornPage5Item::new);
	public static final DeferredHolder<Item, Item> GRENADE = REGISTRY.register("grenade", GrenadeItem::new);
	public static final DeferredHolder<Item, Item> SANTA_SPAWN_EGG = REGISTRY.register("santa_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.SANTA, -65536, -13369600, new Item.Properties()));
	public static final DeferredHolder<Item, Item> STRONGER_THAN_YOU = REGISTRY.register("stronger_than_you", StrongerThanYouItem::new);
	public static final DeferredHolder<Item, Item> BEENADE = REGISTRY.register("beenade", BeenadeItem::new);
	public static final DeferredHolder<Item, Item> BEENADE_2 = REGISTRY.register("beenade_2", Beenade2Item::new);
	public static final DeferredHolder<Item, Item> BEENADE_3 = REGISTRY.register("beenade_3", Beenade3Item::new);
	public static final DeferredHolder<Item, Item> REDBLOCK = block(TerribletwoModBlocks.REDBLOCK);
	public static final DeferredHolder<Item, Item> WALL_GRENADE = REGISTRY.register("wall_grenade", WallGrenadeItem::new);
	public static final DeferredHolder<Item, Item> CONE_GRENADE = REGISTRY.register("cone_grenade", ConeGrenadeItem::new);
	public static final DeferredHolder<Item, Item> FLOOR_GRENADE = REGISTRY.register("floor_grenade", FloorGrenadeItem::new);
	public static final DeferredHolder<Item, Item> BUILDING_WALL_GRENADE = REGISTRY.register("building_wall_grenade", BuildingWallGrenadeItem::new);
	public static final DeferredHolder<Item, Item> STAIR_GRENADE = REGISTRY.register("stair_grenade", StairGrenadeItem::new);
	public static final DeferredHolder<Item, Item> THE_RED_BUTTON = REGISTRY.register("the_red_button", TheRedButtonItem::new);
	public static final DeferredHolder<Item, Item> PEEPEE_MAN_SPAWN_EGG = REGISTRY.register("peepee_man_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.PEEPEE_MAN, -256, -256, new Item.Properties()));
	public static final DeferredHolder<Item, Item> EERALD = REGISTRY.register("eerald", EeraldItem::new);
	public static final DeferredHolder<Item, Item> ROSE = block(TerribletwoModBlocks.ROSE);
	public static final DeferredHolder<Item, Item> WEET = REGISTRY.register("weet", WeetItem::new);
	public static final DeferredHolder<Item, Item> END_FLAMES = REGISTRY.register("end_flames", EndFlamesItem::new);
	public static final DeferredHolder<Item, Item> SARCOPHAGUS_BLOCK = block(TerribletwoModBlocks.SARCOPHAGUS_BLOCK);
	public static final DeferredHolder<Item, Item> SARCOPHAGUS_BLOCK_2 = block(TerribletwoModBlocks.SARCOPHAGUS_BLOCK_2);
	public static final DeferredHolder<Item, Item> SUSBUCKET = REGISTRY.register("susbucket", SusbucketItem::new);
	public static final DeferredHolder<Item, Item> DEAD_SUSBUCKET = REGISTRY.register("dead_susbucket", DeadSusbucketItem::new);
	public static final DeferredHolder<Item, Item> DRIPPED_SUSBUCKET = REGISTRY.register("dripped_susbucket", DrippedSusbucketItem::new);
	public static final DeferredHolder<Item, Item> GREEN_ELF_SPAWN_EGG = REGISTRY.register("green_elf_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GREEN_ELF, -13369600, -16751104, new Item.Properties()));
	public static final DeferredHolder<Item, Item> RED_ELF_SPAWN_EGG = REGISTRY.register("red_elf_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.RED_ELF, -65536, -6750208, new Item.Properties()));
	public static final DeferredHolder<Item, Item> C_SPIKE = REGISTRY.register("c_spike", CSpikeItem::new);
	public static final DeferredHolder<Item, Item> MUSKET_BALL_ITEM = REGISTRY.register("musket_ball_item", MusketBallItemItem::new);
	public static final DeferredHolder<Item, Item> GOLDEN_CLAY = REGISTRY.register("golden_clay", GoldenClayItem::new);
	public static final DeferredHolder<Item, Item> MOUSTASCHE = REGISTRY.register("moustasche", MoustascheItem::new);
	public static final DeferredHolder<Item, Item> WARFSTACHE = REGISTRY.register("warfstache", WarfstacheItem::new);
	public static final DeferredHolder<Item, Item> STAROF_DAVID_BLOCK = block(TerribletwoModBlocks.STAROF_DAVID_BLOCK);
	public static final DeferredHolder<Item, Item> BARREL = block(TerribletwoModBlocks.BARREL);
	public static final DeferredHolder<Item, Item> BOOS_SMALL_FIREBALL = REGISTRY.register("boos_small_fireball", BoosSmallFireballItem::new);
	public static final DeferredHolder<Item, Item> BOOS_ARTEMIS_SPAWN_EGG = REGISTRY.register("boos_artemis_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.BOOS_ARTEMIS, -1, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> C_SHAPE_SPAWN_EGG = REGISTRY.register("c_shape_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.C_SHAPE, -6750157, -26215, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SKINNY_SHROOM = block(TerribletwoModBlocks.SKINNY_SHROOM);
	public static final DeferredHolder<Item, Item> GOON_SHROOM = block(TerribletwoModBlocks.GOON_SHROOM);
	public static final DeferredHolder<Item, Item> SONIC_SHOES_BOOTS = REGISTRY.register("sonic_shoes_boots", SonicShoesItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOLDEN_SCAR = REGISTRY.register("golden_scar", GoldenScarItem::new);
	public static final DeferredHolder<Item, Item> LIGHTNING_BOLT = REGISTRY.register("lightning_bolt", LightningBoltItem::new);
	public static final DeferredHolder<Item, Item> TURTLE_SOUP = REGISTRY.register("turtle_soup", TurtleSoupItem::new);
	public static final DeferredHolder<Item, Item> PICKLE_RICK = REGISTRY.register("pickle_rick", PickleRickItem::new);
	public static final DeferredHolder<Item, Item> SOUR_BERRIES = REGISTRY.register("sour_berries", SourBerriesItem::new);
	public static final DeferredHolder<Item, Item> SLOW_BERRIES = REGISTRY.register("slow_berries", SlowBerriesItem::new);
	public static final DeferredHolder<Item, Item> TALL_ROD = block(TerribletwoModBlocks.TALL_ROD);
	public static final DeferredHolder<Item, Item> FLASHBANG = REGISTRY.register("flashbang", FlashbangItem::new);
	public static final DeferredHolder<Item, Item> TALL_ROD_2 = block(TerribletwoModBlocks.TALL_ROD_2);
	public static final DeferredHolder<Item, Item> BEATROOT = REGISTRY.register("beatroot", BeatrootItem::new);
	public static final DeferredHolder<Item, Item> CHRISTMAS_COOKIE = REGISTRY.register("christmas_cookie", ChristmasCookieItem::new);
	public static final DeferredHolder<Item, Item> MIMIC_SONG = REGISTRY.register("mimic_song", MimicSongItem::new);
	public static final DeferredHolder<Item, Item> PLACING_BLOCKS = REGISTRY.register("placing_blocks", PlacingBlocksItem::new);
	public static final DeferredHolder<Item, Item> LIVING_TOMBSTONE = REGISTRY.register("living_tombstone", LivingTombstoneItem::new);
	public static final DeferredHolder<Item, Item> MINING_DIAMONDS = REGISTRY.register("mining_diamonds", MiningDiamondsItem::new);
	public static final DeferredHolder<Item, Item> NOBODYS_HERO = REGISTRY.register("nobodys_hero", NobodysHeroItem::new);
	public static final DeferredHolder<Item, Item> END_FLAMES_BOOK = REGISTRY.register("end_flames_book", EndFlamesBookItem::new);
	public static final DeferredHolder<Item, Item> C_SPIKE_BOOK = REGISTRY.register("c_spike_book", CSpikeBookItem::new);
	public static final DeferredHolder<Item, Item> CRYSTAL_RAIN = REGISTRY.register("crystal_rain", CrystalRainItem::new);
	public static final DeferredHolder<Item, Item> SECRET_ENDING = REGISTRY.register("secret_ending", SecretEndingItem::new);
	public static final DeferredHolder<Item, Item> ATHLETIC_STEVE_SPAWN_EGG = REGISTRY.register("athletic_steve_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.ATHLETIC_STEVE, -10079488, -1, new Item.Properties()));
	public static final DeferredHolder<Item, Item> GOLDEN_FREDDY_SPAWN_EGG = REGISTRY.register("golden_freddy_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.GOLDEN_FREDDY, -154, -154, new Item.Properties()));
	public static final DeferredHolder<Item, Item> BEATKING_SPAWN_EGG = REGISTRY.register("beatking_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.BEATKING, -39322, -52378, new Item.Properties()));
	public static final DeferredHolder<Item, Item> SHAKESPEARE = block(TerribletwoModBlocks.SHAKESPEARE);
	public static final DeferredHolder<Item, Item> GUFF_SOUL = REGISTRY.register("guff_soul", GuffSoulItem::new);
	public static final DeferredHolder<Item, Item> HEARTH_DETECTOR = block(TerribletwoModBlocks.HEARTH_DETECTOR);
	public static final DeferredHolder<Item, Item> LONGPLIER = REGISTRY.register("longplier", LongplierItem::new);
	public static final DeferredHolder<Item, Item> SPRINGTRAP_SPAWN_EGG = REGISTRY.register("springtrap_spawn_egg", () -> new DeferredSpawnEggItem(TerribletwoModEntities.SPRINGTRAP, -16751104, -16777216, new Item.Properties()));
	public static final DeferredHolder<Item, Item> WEEZER = REGISTRY.register("weezer", WeezerItem::new);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
